# Generated by Django 4.2.1 on 2023-06-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_profile_picture'),
        ('core', '0004_delete_event_user_gaccess_token_user_grefresh_token_and_more'),
    ]

    operations = [
    ]
