# Generated by Django 4.2.1 on 2023-06-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_creds_remove_user_gaccess_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_gmail',
        ),
        migrations.AddField(
            model_name='creds',
            name='has_gmail',
            field=models.BooleanField(default=False),
        ),
    ]
