# Generated by Django 4.2.1 on 2023-06-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_creds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creds',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.creds'),
        ),
    ]
