# Generated by Django 4.2.2 on 2023-06-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_creds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='creds',
        ),
    ]
