# Generated by Django 4.1.7 on 2023-03-18 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='QuizModel',
        ),
        migrations.RenameField(
            model_name='difficultyset',
            old_name='quiz',
            new_name='quiz_model',
        ),
    ]
