# Generated by Django 4.1.7 on 2023-03-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_base', '0003_rename_score_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='total_grades',
            field=models.DecimalField(decimal_places=2, default=22, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
