# Generated by Django 4.1.7 on 2023-03-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_base', '0004_quizmodel_total_grades_alter_question_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizmodel',
            old_name='total_grades',
            new_name='total_grades_after_randomizing',
        ),
    ]
