# Generated by Django 4.2.1 on 2023-05-13 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_base', '0006_quizmodel_classroom'),
        ('quiz', '0005_alter_randomquestion_quiz_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_submitted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='randomquestion',
            name='choice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_base.answer'),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
