# Generated by Django 4.1.7 on 2023-03-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='GPA',
            field=models.DecimalField(decimal_places=2, default=3.07, max_digits=3),
            preserve_default=False,
        ),
    ]
