# Generated by Django 4.1.7 on 2023-05-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfiles',
            name='file_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
