# Generated by Django 4.1.7 on 2023-03-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_learner_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='GPA',
            field=models.DecimalField(blank=True, decimal_places=2, default=3.01, max_digits=3),
            preserve_default=False,
        ),
    ]
