# Generated by Django 4.1.7 on 2023-05-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_postfiles_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfiles',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
