# Generated by Django 4.1.7 on 2023-05-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_postfiles_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfiles',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
