# Generated by Django 4.1.7 on 2023-05-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_postfiles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfiles',
            name='file_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
