# Generated by Django 4.1.7 on 2023-05-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_studentworkbook_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentworkbook',
            old_name='course_assignment',
            new_name='course',
        ),
    ]
