# Generated by Django 4.1.7 on 2023-05-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_assignmentsubmission_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseassignment',
            name='course',
        ),
        migrations.DeleteModel(
            name='AssignmentSubmission',
        ),
        migrations.DeleteModel(
            name='CourseAssignment',
        ),
    ]
