# Generated by Django 4.1.7 on 2023-05-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_courseassignment_course_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseEvent',
        ),
    ]
