# Generated by Django 4.2.1 on 2023-06-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_postfiles_file_type'),
        ('dashboard', '0017_delete_courseevent'),
    ]

    operations = [
    ]
