# Generated by Django 4.2.1 on 2023-06-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_merge_20230610_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='GPA',
        ),
    ]
