insert into elms.auth_permission (id, name, content_type_id, codename)
values  (1, 'Can add log entry', 1, 'add_logentry'),
        (2, 'Can change log entry', 1, 'change_logentry'),
        (3, 'Can delete log entry', 1, 'delete_logentry'),
        (4, 'Can view log entry', 1, 'view_logentry'),
        (5, 'Can add permission', 2, 'add_permission'),
        (6, 'Can change permission', 2, 'change_permission'),
        (7, 'Can delete permission', 2, 'delete_permission'),
        (8, 'Can view permission', 2, 'view_permission'),
        (9, 'Can add group', 3, 'add_group'),
        (10, 'Can change group', 3, 'change_group'),
        (11, 'Can delete group', 3, 'delete_group'),
        (12, 'Can view group', 3, 'view_group'),
        (13, 'Can add content type', 4, 'add_contenttype'),
        (14, 'Can change content type', 4, 'change_contenttype'),
        (15, 'Can delete content type', 4, 'delete_contenttype'),
        (16, 'Can view content type', 4, 'view_contenttype'),
        (17, 'Can add session', 5, 'add_session'),
        (18, 'Can change session', 5, 'change_session'),
        (19, 'Can delete session', 5, 'delete_session'),
        (20, 'Can view session', 5, 'view_session'),
        (21, 'Can add user', 6, 'add_user'),
        (22, 'Can change user', 6, 'change_user'),
        (23, 'Can delete user', 6, 'delete_user'),
        (24, 'Can view user', 6, 'view_user');